[package]
name = "murahdahla"
version = "0.2.6"
authors = ["cassidoxa <cassidymoen@gmx.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.10"
dotenv = "0.15.0"
env_logger = "0.7.1"
lazy_static = "1.4.0"
log = "0.4.8"
serde_json = "1.0.44"

[dependencies.diesel]
version = "1.4.3"
default-features = false
features = ["mysql", "chrono", "r2d2"]

[dependencies.reqwest]
version = "0.9.24"
default-features = false
features = ["rustls-tls"]

[dependencies.serenity]
version = "0.8.0"
features = ["cache", "standard_framework", "rustls_backend"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "abort"
