[package]
name = "murahdahla"
version = "0.2.1"
authors = ["cassidoxa <cassidymoen@gmx.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
dotenv = "0.14.1"
env_logger = "0.7.0"
fnv = "1.0.6"
lazy_static = "1.4.0"
log = "0.4.8"
reqwest = "0.9.20"
serde_json = "1.0.40"

[dependencies.diesel]
version = "1.4.2"
default-features = false
features = ["mysql", "chrono", "r2d2"]

[dependencies.serenity]
version = "0.7.1"
features = ["cache", "framework", "standard_framework", "rustls_backend"]

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = "abort"
